name: Lint & Format Project

on: ['push', 'pull_request']

jobs:
  linting:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
      - name: Lint
        run: |
          npm ci
          npm run lint

  formatting:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Format
        run: |
          npm ci
          npm run fmt
